# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ESSEB2 <- function(l, n, Q, size, nodes, whts, lambda_Y_new, Lambda_Y_new, beta_X, delta_i, dgamma_Q, Lambda_b_nozero, Y_eq_Yhat, Y_geq_Yhat, X) {
    .Call(`_transmdl_ESSEB2`, l, n, Q, size, nodes, whts, lambda_Y_new, Lambda_Y_new, beta_X, delta_i, dgamma_Q, Lambda_b_nozero, Y_eq_Yhat, Y_geq_Yhat, X)
}

ddloglik_transmdl <- function(n, delta, Z, beta, E) {
    .Call(`_transmdl_ddloglik_transmdl`, n, delta, Z, beta, E)
}

shoot <- function(X, y, beta_ini_s, lamb_s) {
    .Call(`_transmdl_shoot`, X, y, beta_ini_s, lamb_s)
}

